before_script:
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive
    apt-get install -y
    build-essential
    cmake
    libblas-dev
    liblapack-dev
    libmetis-dev
    libomp-dev
    libtbb-dev
    ninja-build
    nvidia-cuda-toolkit

ubuntu:build:
  image: ubuntu:rolling
  stage: build
  tags:
    - docker
  script:
    - mkdir build
    - cmake -S . -B build/ -GNinja -DCMAKE_BUILD_TYPE=Debug
    - cmake --build build/
  artifacts:
    paths:
      - build/


ubuntu:package:
  image: ubuntu:rolling
  stage: deploy
  tags:
    - docker
  script:
    - cd build
    - cpack -G ZIP
  artifacts:
    paths:
      - build/*.zip
  needs: ['ubuntu:build']
