default:
  tags:
    - docker

.ubuntu_setup_template: &ubuntu_setup
  before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive
      apt-get install -y
      build-essential
      cmake
      gfortran
      libblas-dev
      liblapack-dev
      libmetis-dev
      libomp-dev
      libtbb-dev
      ninja-build
      nvidia-cuda-toolkit

.mingw_setup_template: &mingw_setup
  before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive
      apt-get install -y
      g++-mingw-w64
      gcc-mingw-w64
      cmake
      libblas-dev
      liblapack-dev
      libmetis-dev
      libomp-dev
      libtbb-dev
      ninja-build
      nvidia-cuda-toolkit

ubuntu:build:
  image: ubuntu:rolling
  stage: build
  <<: *ubuntu_setup
  script:
    - mkdir build
    - cmake -S . -B build/ -GNinja -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Debug
    - cmake --build build/
  artifacts:
    paths:
      - build/

ubuntu:package:
  image: ubuntu:rolling
  stage: deploy
  <<: *ubuntu_setup
  script:
    - cd build
    - cpack -G ZIP
  artifacts:
    paths:
      - build/*.zip
  needs: ['ubuntu:build']
