name: Linux

on: [push, pull_request]

jobs:
  build:
    name: GCC-${{matrix.build_type}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
          build_type: [Release, Debug]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Dependencies
      shell: bash
      run: |
        sudo apt-get update
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -y \
          build-essential \
          cmake \
          gcc-8 \
          gfortran \
          libblas-dev \
          liblapack-dev \
          libmetis-dev \
          libomp-dev \
          libtbb-dev \
          ninja-build \
          nvidia-cuda-toolkit

    - name: Configure
      shell: bash
      run: |
        cmake -S . -B build_${{matrix.build_type}}/ \
              -G Ninja \
              -D CUDA_HOST_COMPILER=/usr/bin/gcc-8
    - name: Build
      shell: bash
      run: |
        cmake --build build_${{matrix.build_type}}/ \
              --config ${{matrix.build_type}}
