name: macOS

on: [push, pull_request]

jobs:
  build:
    name: AppleClang-${{matrix.build_type}}
    runs-on: macos-10.15
    strategy:
      fail-fast: true
      matrix:
          build_type: [Release, Debug]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@master
      with:
        version: 1.10.0

    - name: Configure
      shell: bash
      run: |
        cmake -S . -B ${{runner.workspace}}/build_${{matrix.name}}_${{matrix.build_type}} \
              -G Ninja
    - name: Build
      run: |
        cmake --build ${{runner.workspace}}/build_${{matrix.name}}_${{matrix.build_type}} \
              --config ${{matrix.build_type}}
