name: Windows

on: [push, pull_request]

jobs:
  build-mingw:
    name: ${{matrix.sys}}-${{matrix.env}}-${{matrix.build_type}}-${{matrix.lib}}-${{matrix.components}}
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    env:
      CCACHE_DIR: ${{github.workspace}}/ccache
    strategy:
      fail-fast: true
      matrix:
        build_type: [Release, Debug]
        sys: [mingw32, mingw64]
        lib: [shared, static]
        components: [minimal, lgpl, gpl]
        include:
          - sys: mingw32
            env: i686
          - sys: mingw64
            env: x86_64

    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        install: >-
          mingw-w64-${{matrix.env}}-ccache
          mingw-w64-${{matrix.env}}-cmake
          mingw-w64-${{matrix.env}}-gcc
          mingw-w64-${{matrix.env}}-gcc-fortran
          mingw-w64-${{matrix.env}}-intel-tbb
          mingw-w64-${{matrix.env}}-lapack
          mingw-w64-${{matrix.env}}-metis
          mingw-w64-${{matrix.env}}-ninja
          mingw-w64-${{matrix.env}}-openblas
          mingw-w64-${{matrix.env}}-openmp
          unzip
          wget

    - name: Setup Environment
      if: ${{matrix.build_type == 'Release'}}
      run: |
        echo 'CFLAGS=-flto' >> ~/.bash_profile
        echo 'CXXFLAGS=-flto' >> ~/.bash_profile

    - name: Cache Build
      id: cache-build
      uses: actions/cache@v2
      with:
        path: ${{env.CCACHE_DIR}}
        key: ${{runner.os}}-${{matrix.sys}}-${{matrix.env}}-ccache-${{github.run_id}}
        restore-keys: ${{runner.os}}-${{matrix.sys}}-${{matrix.env}}-ccache-

    - name: Configure
      env:
        CC: ${{matrix.env}}-w64-mingw32-gcc
        CXX: ${{matrix.env}}-w64-mingw32-g++
      run: |
        cmake -S . -B build_${{matrix.build_type}}/ \
              -DBUILD_SHARED_LIBS=${{matrix.lib == 'shared'}} \
              -DCMAKE_C_COMPILER_LAUNCHER:FILEPATH=ccache \
              -DCMAKE_CXX_COMPILER_LAUNCHER:FILEPATH=ccache \
              -DCMAKE_Fortran_COMPILER_LAUNCHER:FILEPATH=ccache \
              -DCMAKE_INSTALL_PREFIX:PATH=./install \
              -DWITH_GPL=${{matrix.components == 'gpl'}} \
              -DWITH_LGPL=${{contains(matrix.components, 'gpl')}} \
              -G Ninja

    - name: Build
      run: |
        cmake --build build_${{matrix.build_type}}/ \
              --config ${{matrix.build_type}}

    - name: Install
      run: |
        cmake --build build_${{matrix.build_type}}/ \
              --config ${{matrix.build_type}} \
              --target install

  build-msvc:
    name: ${{matrix.msvc}}-${{matrix.build_type}}-${{matrix.lib}}-${{matrix.components}}
    runs-on: ${{matrix.os}}
    env:
      CCACHE_DIR: ${{github.workspace}}/ccache
    defaults:
      run:
        shell: powershell
    strategy:
      fail-fast: true
      matrix:
        build_type: [Release, Debug]
        msvc: [VS-16-2019, VS-17-2022]
        sys: [mingw64]
        lib: [shared, static]
        components: [minimal, lgpl, gpl]
        include:
          - sys: mingw64
            env: x86_64
            system: Win64
          - msvc: VS-16-2019
            generator: "Visual Studio 16 2019"
            os: windows-2019
            marker: vc16
          - msvc: VS-17-2022
            generator: "Visual Studio 17 2022"
            os: windows-2022
            marker: vc17

    steps:
    - uses: actions/checkout@v2

    - name: Query Tags
      run: |
        git fetch --unshallow --tags

    - uses: ashutoshvarma/setup-ninja@master
      with:
        version: 1.10.0

    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        path-type: inherit
        install: >-
          wget
          mingw-w64-${{matrix.env}}-ccache
          mingw-w64-${{matrix.env}}-gcc-fortran

    - name: Download LAPACK
      if: steps.cache-lapack.outputs.cache-hit != 'true'
      shell: msys2 {0}
      run: |
        wget https://github.com/Reference-LAPACK/lapack/archive/refs/tags/v3.10.0.tar.gz
        tar xvf v3.10.0.tar.gz

    - name: Build LAPACK
      if: steps.cache-lapack.outputs.cache-hit != 'true'
      shell: msys2 {0}
      run: |
        cmake -S lapack-3.10.0 -B build_lapack_${{matrix.build_type}}/ \
              -DBUILD_SHARED_LIBS=ON \
              -DCMAKE_C_COMPILER_LAUNCHER:FILEPATH=$(which ccache) \
              -DCMAKE_Fortran_COMPILER_LAUNCHER:FILEPATH=$(which ccache) \
              -DCMAKE_GNUtoMS=ON \
              -DCMAKE_INSTALL_PREFIX=./install \
              -G Ninja

        cmake --build build_lapack_${{matrix.build_type}}/ \
              --config ${{matrix.build_type}} \
              --target install

    - name: Cache LAPACK
      id: cache-lapack
      uses: actions/cache@v2
      with:
        path: |
          ${{env.CCACHE_DIR}}
          ${{github.workspace}}/install
        key: ${{runner.os}}-lapack-3.10

    - name: Setup MSYS2 Environment
      shell: msys2 {0}
      run: |
        echo "$(cygpath -m /${{matrix.sys}}/bin)" >> $GITHUB_PATH

    - name: Setup Environment
      run: |
        echo "${{github.workspace}}/install/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "VERSION_SUFFIX=$(git describe --tags)-${{matrix.marker}}-${{matrix.system}}-${{matrix.build_type}}-${{matrix.lib}}-${{matrix.components}}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Configure
      run: |
        cmake -S . -B build_${{matrix.build_type}}/ `
              -A x64 `
              -DBLAS_blas_LIBRARY=${{github.workspace}}/install/lib/libblas.lib `
              -DBUILD_SHARED_LIBS=${{matrix.lib == 'shared'}} `
              -DCMAKE_INSTALL_PREFIX:PATH=${{github.workspace}}/install-suitesparse `
              -DLAPACK_lapack_LIBRARY=${{github.workspace}}/install/lib/liblapack.lib `
              -DWITH_FORTRAN=OFF `
              -DWITH_GPL=${{matrix.components == 'gpl'}} `
              -DWITH_LGPL=${{contains(matrix.components, 'gpl')}} `
              -G "${{matrix.generator}}"

    - name: Build
      run: |
        cmake --build build_${{matrix.build_type}}/ `
              --config ${{matrix.build_type}}

    - name: Install
      run: |
        cmake --build build_${{matrix.build_type}}/ `
              --config ${{matrix.build_type}} `
              --target install

    - name: Prepare Deployment
      run: |
        New-Item -ItemType "directory" -Path "${{github.workspace}}/deploy"
        Copy-Item -Path "${{github.workspace}}/install/*" -Destination "${{github.workspace}}/deploy/" -Recurse -Force
        Copy-Item -Path "${{github.workspace}}/install-suitesparse/*" -Destination "${{github.workspace}}/deploy/" -Recurse -Force
        Compress-Archive -Path "${{github.workspace}}/deploy/*" -Destination "SuiteSparse-${{env.VERSION_SUFFIX}}.zip"

    - uses: actions/upload-artifact@v2
      with:
        name: SuiteSparse-${{env.VERSION_SUFFIX}}
        path: |
          deploy/

    - name: Deploy
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/') && matrix.lib == 'shared'
      with:
        files:
          SuiteSparse-${{env.VERSION_SUFFIX}}.zip
